paths:
  glmsingle: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle"
  #fmriprep: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/fmripreps/aotfull_preprocs/fullpreproc_forcesyn_endfix" 
  preproced: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/aot_prep"
  bids: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/bids/aot"
  videos: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/stimuli/rescaled_final" 
  pictures: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/stimuli/pictures"
  video_annotations: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/stimuli/annotations"
  AOTdesignsettings: "/research/FGB-CognitivePsychology-Knapen/szh208/AOT_code_repos/arrow_of_time_experiment/aot/data/experiment/settings/main"
  # sbert_embeddings: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/DLoutputs/sbert/simple_describe_en_clean_embeddings"
  # llama_descriptions: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/DLoutputs/videollama_describe/simple_describe_en_clean"
  # motion_energy: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/temp/motion_energy_features/video_features"
  # prf: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/prf"
  prf: "/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/prf_noshift"

parameters:
  run_number: 10

